CREATE TABLE  MUSTERI(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD_SOYAD VARCHAR(255),
	TELEFON VARCHAR(255),
	ADRES VARCHAR(255),
	SEHIR_ID INT);
	
	CREATE TABLE  ACCOUNTS(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	YETKI_ID INT,
	SIFRE VARCHAR(255),
	PERSONEL_ID INT);
	
	CREATE TABLE  KATEGORI(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	ADI VARCHAR(255),
	PARENT_ID INT);
	
	CREATE TABLE  PERSONEL(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD_SOYAD VARCHAR(255),
	EMAIL VARCHAR(255));
	
	CREATE TABLE  SATIS(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	MUSTERI_ID INT,
	PERSONEL_ID INT,
	URUN_ID INT,
	ADET INT,
	TARIH DATE);
	
	CREATE TABLE  STOK(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	PERSONEL_ID INT,
	URUN_ID INT,
	TARIH DATE,
	ADET INT);
	
	CREATE TABLE  URUNLER(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD VARCHAR(255),
	KATEGORI_ID INT,
	TARIH DATE,
	FIYAT DECIMAL);
	
	CREATE TABLE  YETKILER(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	ADI VARCHAR(255));
	
	
	