CREATE TABLE IF NOT EXIST MUSTERI(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD_SOYAD VARCHAR(255),
	TELEFON VARCHAR(255),
	ADRES VARCHAR(255),
	SEHIR_ID INT);
	
	CREATE TABLE IF NOT EXIST ACCOUNTS(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	YETKI_ID INT,
	SIFRE VARCHAR(255),
	PERSONEL_ID INT);
	
	CREATE TABLE IF NOT EXIST KATEGORI(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	ADI VARCHAR(255),
	INT PARENT_ID);
	
	CREATE TABLE IF NOT EXIST PERSONEL(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD_SOYAD VARCHAR(255),
	EMAIL VARCHAR(255);
	
	CREATE TABLE IF NOT EXIST SATIS(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	MUSTERI_ID INT,
	PERSONEL_ID INT,
	URUN_ID INT,
	ADET INT,
	TARIH DATE);
	
	CREATE TABLE IF NOT EXIST STOK(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	PERSONEL_ID INT,
	URUN_ID INT,
	TARIH DATE,
	ADET INT);
	
	CREATE TABLE IF NOT EXIST URUNLER(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD VARCHAR(255),
	KATEGORI_ID INT,
	TARIH DATE,
	FIYAT DECIMAL);
	
	CREATE TABLE IF NOT EXIST YETKILER(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	ADI VARCHAR(255));
	
	
	