CREATE TABLE IF NOT EXIST MUSTERI(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	AD_SOYAD VARCHAR(255),
	TELEFON VARCHAR(255),
	ADRES VARCHAR(255),
	SEHIR_ID INT);
	
	CREATE TABLE IF NOT EXIST ACCOUNTS(
	ID INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
	YETKI_ID INT,
	SIFRE VARCHAR(255),
	PERSONEL_ID INT);
	
	--DEVAM
	